# Generated by Django 3.1.5 on 2021-01-05 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='date_post',
            new_name='date_posted',
        ),
    ]
